#include "tree_internal.hpp"

namespace ctboost {

int Tree::BuildNode(const HistMatrix& hist,
                    const std::vector<float>& gradients,
                    const std::vector<float>& hessians,
                    const std::vector<float>& weights,
                    std::vector<std::size_t>& row_indices,
                    std::size_t row_begin,
                    std::size_t row_end,
                    int depth,
                    const TreeBuildOptions& options,
                    GpuHistogramWorkspace* gpu_workspace,
                    const GpuHistogramSnapshot* precomputed_gpu_histogram,
                    bool precomputed_gpu_histogram_resident,
                    const NodeHistogramSet* precomputed_node_stats,
                    double precomputed_histogram_ms,
                    const std::vector<int>* node_allowed_features,
                    const std::vector<int>* active_interaction_groups,
                    double leaf_lower_bound,
                    double leaf_upper_bound,
                    const TrainingProfiler* profiler,
                    const LinearStatistic& statistic_engine,
                    std::vector<LeafRowRange>* leaf_row_ranges_out,
                    int* leaf_count) {
  return options.use_gpu
             ? BuildNodeGpu(hist,
                            gradients,
                            hessians,
                            weights,
                            row_indices,
                            row_begin,
                            row_end,
                            depth,
                            options,
                            gpu_workspace,
                            precomputed_gpu_histogram,
                            precomputed_gpu_histogram_resident,
                            precomputed_node_stats,
                            precomputed_histogram_ms,
                            node_allowed_features,
                            active_interaction_groups,
                            leaf_lower_bound,
                            leaf_upper_bound,
                            profiler,
                            statistic_engine,
                            leaf_row_ranges_out,
                            leaf_count)
             : BuildNodeCpu(hist,
                            gradients,
                            hessians,
                            weights,
                            row_indices,
                            row_begin,
                            row_end,
                            depth,
                            options,
                            gpu_workspace,
                            precomputed_gpu_histogram,
                            precomputed_gpu_histogram_resident,
                            precomputed_node_stats,
                            precomputed_histogram_ms,
                            node_allowed_features,
                            active_interaction_groups,
                            leaf_lower_bound,
                            leaf_upper_bound,
                            profiler,
                            statistic_engine,
                            leaf_row_ranges_out,
                            leaf_count);
}

}  // namespace ctboost
